config/routes.rb
Rails.application.routes.draw do

  get 'mortality_report/show'
  get 'mortality_report/report'
  resources :mortality_forms
  resources :pens
  resources :leases
  resources :divers

  root "user_sessions#new"
   # root "leases#index"
  resource :user_sessions do
    get :new
    get :success
  end

  resources :users, only: [:new, :create] do
    resources :profile, only: [:show, :index, :edit, :update]
    resources :posts, only: [:create]
    resources :feed, only: [:show]
    member do
      get :following, :followers
    end

  end

  resources :relationships, only: [:create, :destroy]
end

app/models/pen.rb
class Pen < ApplicationRecord
  belongs_to :lease
  has_many :mortality_forms
end

app/controllers/pens_controller.rb
class PensController < ApplicationController
  before_action :set_pen, only: [:show, :edit, :update, :destroy]

  # GET /pens
  def index
    @pens = Pen.all
  end

  # GET /pens/1
  def show
    respond_to do |format|
      format.html do
causes = [ :bird_strikes, :seal_strikes, :skinny, :deformities, :unknown ]
dates = MortalityForm.all.group_by{|x| x.date}
@reports = MortalityForm.where(date: (Time.now - 1.week)..Time.now, pen: @pen).includes(:diver)
.group_by{|x| x.date.strftime("%Y-%m-%d")}
@causes = causes.map { |cause| { name: cause.id2name.split("_").join(" ").capitalize, data: dates.map{ |date, v| [[date.strftime("%Y-%m-%d"), v[0][cause]] ] }.sum   } }

@mortalities ||= MortalitySearcher.new(
  start_date: Date.current,
  end_date: Date.current
).run
@mortality_totals = totals

end
  format.js do
    @reports = mortality_search
  end

end

  end

  # GET /pens/new
  def new
    @leases = Lease.all
    @pen = Pen.new
    @pens = Pen.all
  end

  # GET /pens/1/edit
  def edit
  end

  def mortality_search
    start_date = params[:search_begin].to_date
    end_date = params[:search_end].to_date
    @mortality_search ||= MortalityForm.where(date: start_date..end_date, pen: @pen).includes(:diver).group_by{|x| x.date.strftime("%Y-%m-%d")}
  end

  def search
    @facade = Profiles::ProfileIndexFacade.new(query: params[:query]).run
  end

  # POST /pens
  def create
    @pen = Pen.new(pen_params)

    if @pen.save
      redirect_to @pen, notice: 'Pen was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /pens/1
  def update
    if @pen.update(pen_params)
      redirect_to @pen, notice: 'Pen was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /pens/1
  def destroy
    @pen.destroy
    redirect_to pens_url, notice: 'Pen was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pen
      @pen = Pen.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def pen_params
      params.require(:pen).permit(:name, :lease_id, :latitude, :longitude)
    end

    def totals
      {

        bird_strikes: @mortalities.map{|total| total.bird_strikes}.sum,
        seal_strikes: @mortalities.map{|total| total.seal_strikes}.sum,
        skinny: @mortalities.map{|total| total.skinny}.sum,
        deformities: @mortalities.map{|total| total.deformities}.sum,
        unknown: @mortalities.map{|total| total.unknown}.sum
      }
    end
end

app/helpers/pens_helper.rb
module PensHelper
end

app/views/pens/_form.html.erb
<%= form_with(model: pen, local: true) do |form| %>
  <% if pen.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pen.errors.count, "error") %> prohibited this pen from being saved:</h2>

      <ul>
        <% pen.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">

    <div class="col-2">
      <div class="form-group">
        <%= label_tag :date, 'Name', class: 'control-label' %><br />
        <%= form.text_field :name, class: 'form-control'  %>
          <%# <%= form.date_select :report_date, :placeholder => Date.current, class: 'datepicker' %>
      </div>
    </div>

    <div class="col-2">
      <div class="form-group">
        <%= label_tag :date, 'Date', class: 'control-label' %><br />
        <%= form.date_field :report_date,:value => Time.now.strftime('%Y-%m-%d'), class: 'form-control' %>
          <%# <%= form.date_select :report_date, :placeholder => Date.current, class: 'datepicker' %>
      </div>
    </div>

    <div class="form-group">
      <div class="field">
        <%= form.label :latitude %>
        <%= form.text_field :latitude, class: 'form-control'  %>
      </div>
    </div>

    <div class="form-group">
      <div class="field">
        <%= form.label :longitude %>
        <%= form.text_field :longitude, class: 'form-control'  %>
      </div>
    </div>

    <div class="col-2">
      <div class="form-group">
        <%# <%= label_tag :email, 'Lease', class: 'control-label' %><br /> %>
        <%# <%= form.select :lease_id, options_from_collection_for_select(@leases, "id", "name"), {},  class: 'form-control select' %> %>
      </div>
    </div>
  </div>


  <div class="actions">
    <%= form.submit "Update", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/pens/edit.html.erb
<div class="row">
    <div class="col-md-12 mt-4">

<h1>Editing Pen</h1>

<%= render 'form', pen: @pen %>

<%= link_to 'Show', @pen %> |
<%= link_to 'Back', pens_path %>

</div>
</div>

app/views/pens/index.html.erb
<p id="notice"><%= notice %></p>

<div class='row'>
  <div class='col-md-12 space-between' style="display: flex;
    justify-content: space-between;">
    <h1>Pens</h1>
    <div>
      <%= link_to new_pen_path, class: "btn btn-success" do |x| %>
        Create Pen <span class="ml-2"><%= fa_icon "plus"%></span>
      <% end %>

    </div>

  </div>
</div>
<hr>

<div class="row">
  <div class="col-md-12">

    <table class="table table-striped table-bordered text-center">
      <thead class="table-light">
        <tr>
          <th>Name</th>
          <th>Lease</th>
          <th>Latitude</th>
          <th>Longitude</th>
        </tr>
      </thead>

      <tbody>
        <% @pens.each do |pen| %>
          <tr>
            <td><%= link_to pen.name, pen %></td>
            <td><%= link_to pen.lease.name, pen.lease %></td>
            <td><%= pen.latitude %></td>
            <td><%= pen.longitude %></td>

            <td class="action-td">
              <div class="btn-group">
                <%= link_to pen do %>
                <button type="button" class="btn btn-primary">
                  View
                </button>
                <% end %>

                <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <span class="sr-only">Toggle Dropdown</span>
                </button>
                <div class="dropdown-menu">


                  <%= link_to 'Edit', edit_pen_path(pen), class: "dropdown-item" %>

                  <div class="dropdown-divider"></div>
                  <%= link_to pen, method: :delete,  data: { confirm: 'Are you sure?' }, class: "dropdown-item" do |x| %>
                    <span class="trash-icon mr-2">Delete</span><span class="trash-icon mr-2"><%= fa_icon "trash"%></span>
                  <% end %>
                </div>
              </div>
            </td>

          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>

<br>




<script>
  // Initialize and add the map
  function initMap() {
  var uluru = {lat: -25.344, lng: 131.036};
  var uluru_2 = {lat: -22.344, lng: 119.036};
  // The map, centered at Uluru
  var map = new google.maps.Map(
  document.getElementById('map'), {zoom: 4, center: uluru});
  // The marker, positioned at Uluru
  var markers = new google.maps.Marker({position: uluru_2, map: map});
  var marker = new google.maps.Marker({position: uluru, map: map});
  }
</script>

app/views/pens/new.html.erb
  <h1>New Pen</h1>
    <%= render 'form', pen: @pen %>

  <%= link_to 'Back', pens_path %>

app/views/pens/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-12">

    <div class='row'>
      <div class='col-md-12 space-between'>
        <div class='space-between h-center'>
          <%= link_to pens_path, class: "text-primary" do %>
            <%= fa_icon "arrow-left 2x"%>
          <% end %>
          <h1 class="mb-0 ml-3"><%= @pen.name %></h1>
          </div>
        <div>
          <%= link_to edit_pen_path(@pen), class: "btn btn-primary" do |x| %>
        <%= fa_icon "edit"%><span class="ml-2"> Edit Pen</span>
          <% end %>
        </div>

      </div>
    </div>
    <hr>

    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" id="detail-tab" data-toggle="tab" href="#details" role="tab" aria-controls="details" aria-selected="true">Details</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="false">Charts</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Reports</a>
      </li>

    </ul>
    <div class="tab-content" id="myTabContent">

      <div class="tab-pane fade show active" id="details" role="tabpanel" aria-labelledby="details-tab">
        <div class="row">


          <!-- <ul> -->
             <%# <% @mortadlity_totals.each do |k,v| %>
               <%# <%= "#{k.id2name.split("_").join(" ").capitalize} -  #{v}" %>
            <%# <% end %>
          <!-- </ul> -->

          <div class="col-md-6 mt-4">
            <p>
              <strong>Lease:</strong>
              <%= @pen.lease.name %>
            </p>
            <p>
              <strong>Latitude:</strong>
              <%= @pen.latitude %>
            </p>
            <p>
              <strong>Longitude:</strong>
              <%= @pen.longitude %>
            </p>

            <h4> Total Mortalities:</h4>

            <table class="table table-striped table-bordered table-sm">
              <thead class="table-light">
                <tr class="text-center">
                  <th>Bird strikes</th>
                  <th>Seal strikes</th>
                  <th>Skinny</th>
                  <th>Deformities</th>
                  <th>Unknown</th>
                </tr>
              </thead>

              <tbody>
                <tr class="text-center">
                  <td><%= @mortality_totals[:bird_strikes] %></td>
                  <td><%= @mortality_totals[:seal_strikes] %></td>
                  <td><%= @mortality_totals[:skinny] %></td>
                  <td><%= @mortality_totals[:deformities] %></td>
                  <td><%= @mortality_totals[:unknown] %></td>
                </tr>
              </tbody>
            </table>
          </div>

          <div class="col-md-6 mt-4">
            <div id="map" style='width: 100%; height: 400px;'></div>
          </div>

        </div>
      </div>

      <div class="tab-pane fade" id="home" role="tabpanel" aria-labelledby="home-tab">
        <div class="row">
          <div class="col-md-12 mb-5">
            <%= line_chart @causes %>
          </div>
          <div class="col-md-6 mb-5 mt-5">
            <%= pie_chart  @mortality_totals %>
          </div>
          <div class="col-md-6 mb-5 mt-5">
            <%= column_chart @causes %>
          </div>
          <div class="col-md-12 mb-5 mt-5">
            <%= area_chart @causes %>
            <!-- <div class="col-md-12 mt-5 mb-5"> -->
              <%# <%= bar_chart @causes %>
            <!-- </div> -->
          </div>
        </div>
      </div>

      <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
        <div class="row">
          <div class="col-md-12 mt-4">
            <h2>Mortaility Reports</h2>
            <hr>
          </div>


          <div class="row">
            <div class="col-6">
              <%= form_tag pen_path, class: "form", method: :get, remote: true do |form|%>

              <div class="form-group">
                <%= label_tag :date, 'Start Date', class: 'control-label' %><br />
                <%= date_field_tag(:search_begin, (Time.now - 1.week).strftime('%Y-%m-%d'), class: 'form-control') %>
              </div>
            </div>

            <div class="col-6">
              <div class="form-group">
                <%= label_tag :date, 'End Date', class: 'control-label' %><br />
                <%= date_field_tag(:search_end, Time.now.strftime('%Y-%m-%d'), class: 'form-control') %>
              </div>
            </div>

            <% end %>
            <div class="col-12">
              <%= submit_tag "Search", class: "btn btn-success" %>
            </div>
          </div>



          <div id="mortality_forms">
            <%= render 'shared/mortality_reports', reports: @reports%>
          </div>

          <div class="col-md-6">
            <div id="map" style='width: 100%; height: 400px;'>
            </div>
          </div>
        </div>
      </div>


    </div>
  </div>

<%= link_to 'Edit', edit_pen_path(@pen) %> |
<%= link_to 'Back', pens_path %>



<script>


  var lat = <%= @pen.latitude %>

  var lng = <%= @pen.longitude %>

  // Initialize and add the map
  function initMap() {

  var uluru = {lat: lat, lng: lng};
  // The map, centered at Uluru
  var map = new google.maps.Map(
  document.getElementById('map'), {zoom: 4, center: uluru});
  // The marker, positioned at Uluru
  var marker = new google.maps.Marker({position: uluru, map: map});
  }
</script>

app/views/pens/show.js.erb
$('#mortality_forms').html("<%= j render "shared/mortality_reports", reports: @reports %>");