config/routes.rb
Rails.application.routes.draw do

  get 'mortality_report/show'
  get 'mortality_report/report'
  resources :mortality_forms
  resources :pens
  resources :leases
  resources :divers

  root "user_sessions#new"
   # root "leases#index"
  resource :user_sessions do
    get :new
    get :success
  end

  resources :users, only: [:new, :create] do
    resources :profile, only: [:show, :index, :edit, :update]
    resources :posts, only: [:create]
    resources :feed, only: [:show]
    member do
      get :following, :followers
    end

  end

  resources :relationships, only: [:create, :destroy]
end

app/models/diver.rb
class Diver < ApplicationRecord
  has_many :mortality_forms



  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def initials
    "#{self.first_name.first}#{self.last_name.first}"
  end

end

app/controllers/divers_controller.rb
class DiversController < ApplicationController
  before_action :set_diver, only: [:show, :edit, :update, :destroy]

  # GET /divers
  def index
    @divers = Diver.all
  end

  # GET /divers/1
  def show
  end

  # GET /divers/new
  def new
    @diver = Diver.new
  end

  # GET /divers/1/edit
  def edit
  end

  # POST /divers
  def create
    @diver = Diver.new(diver_params)

    if @diver.save
      redirect_to @diver, notice: 'Diver was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /divers/1
  def update
    if @diver.update(diver_params)
      redirect_to @diver, notice: 'Diver was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /divers/1
  def destroy
    @diver.destroy
    redirect_to divers_url, notice: 'Diver was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diver
      @diver = Diver.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def diver_params
      params.require(:diver).permit(:first_name, :last_name, :email, :contact, :address, :secondary_contact)
    end
end

app/helpers/divers_helper.rb
module DiversHelper
end

app/views/divers/_form.html.erb
<%= form_with(model: diver, local: true) do |form| %>
  <% if diver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(diver.errors.count, "error") %> prohibited this diver from being saved:</h2>

      <ul>
        <% diver.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div class="field">
    <%= form.label :first_name, class: 'control-label' %>
    <%= form.text_field :first_name, class: 'form-control' %>
  </div>
</div>

  <div class="form-group">
    <div class="field">
    <%= form.label :last_name, class: 'control-label' %>
    <%= form.text_field :last_name, class: 'form-control' %>
  </div>
</div>

  <div class="form-group">
    <div class="field">
    <%= form.label :email, class: 'control-label' %>
    <%= form.text_field :email, class: 'form-control' %>
  </div>
</div>

  <div class="form-group">
    <div class="field">
    <%= form.label :contact, class: 'control-label' %>
    <%= form.text_field :contact, class: 'form-control' %>
  </div>
</div>

  <div class="form-group">
    <div class="field">
    <%= form.label :address, class: 'control-label' %>
    <%= form.text_field :address, class: 'form-control' %>
  </div>
</div>

  <div class="form-group">
    <div class="field">
    <%= form.label :secondary_contact, class: 'control-label' %>
    <%= form.text_field :secondary_contact, class: 'form-control' %>
  </div>
</div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/divers/index.html.erb
<p id="notice"><%= notice %></p>

<div class='row'>
  <div class='col-md-12 space-between'>
    <h1>Divers</h1>
    <div>
      <%= link_to new_diver_path, class: "btn btn-success" do |x| %>
      Create Diver <span class="ml-2"><%= fa_icon "plus"%></span>
      <% end %>
    </div>

  </div>
</div>
<hr>


<table class="table table-striped table-bordered text-center">
  <thead class="table-light">
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <!-- <th>Email</th> -->
      <th>Contact</th>
      <!-- <th>Address</th> -->
      <!-- <th>Secondary contact</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @divers.each do |diver| %>
      <tr>
        <td><%= diver.first_name %></td>
        <td><%= diver.last_name %></td>
        <%# <%= diver.email %>
        <td><%= diver.contact %></td>
        <%# <%= diver.address %>
        <%# <%= diver.secondary_contact %>

        <td class="action-td">
          <div class="btn-group">
            <%= link_to diver do %>
            <button type="button" class="btn btn-primary">
              View
            </button>
            <% end %>

            <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="sr-only">Toggle Dropdown</span>
            </button>
            <div class="dropdown-menu">


              <%= link_to 'Edit', edit_diver_path(diver), class: "dropdown-item" %>

              <div class="dropdown-divider"></div>
              <%= link_to diver, method: :delete,  data: { confirm: 'Are you sure?' }, class: "dropdown-item" do |x| %>
                <span class="trash-icon mr-2">Delete</span><span class="trash-icon mr-2"><%= fa_icon "trash"%></span>
              <% end %>
            </div>
          </div>
        </td>

      </tr>

    <% end %>
  </tbody>
</table>

<br>

app/views/divers/show.html.erb
<p id="notice"><%= notice %></p>

<div class='col-md-12 space-between h-center'>

        <!-- <span> -->
        <div class='space-between h-center'>
          <%= link_to divers_path, class: "text-primary" do %>
            <%= fa_icon "arrow-left 2x text-primary"%>
          <% end %>
        <!-- </span> -->

      <h1 class="mb-0 ml-3"><%= @diver.full_name %></h1>
    </div>
  <div>
    <%= link_to edit_diver_path(@diver), class: "btn btn-primary" do |x| %>
  <%= fa_icon "edit"%><span class="ml-2"> Edit Diver</span>
    <% end %>
  </div>

</div>
<hr>
<div class="col-md-12">
<p>
  <strong>First name:</strong>
  <%= @diver.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @diver.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @diver.email %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @diver.contact %>
</p>

<p>
  <strong>Address:</strong>
  <%= @diver.address %>
</p>

<p>
  <strong>Secondary contact:</strong>
  <%= @diver.secondary_contact %>
</p>
</div>