config/routes.rb
Rails.application.routes.draw do

  get 'mortality_report/show'
  get 'mortality_report/report'
  resources :mortality_forms
  resources :pens
  resources :leases
  resources :divers

  root "user_sessions#new"
   # root "leases#index"
  resource :user_sessions do
    get :new
    get :success
  end

  resources :users, only: [:new, :create] do
    resources :profile, only: [:show, :index, :edit, :update]
    resources :posts, only: [:create]
    resources :feed, only: [:show]
    member do
      get :following, :followers
    end

  end

  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diver.rb
class Diver < ApplicationRecord
  has_many :mortality_forms



  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def initials
    "#{self.first_name.first}#{self.last_name.first}"
  end

end

app/models/feed.rb
class Feed < ApplicationRecord
  belongs_to :profile
end

app/models/lease.rb
class Lease < ApplicationRecord
  has_many :pens
  has_many :mortality_forms
end

app/models/mortality_form.rb
class MortalityForm  < ApplicationRecord
  belongs_to :lease
  belongs_to :pen
  belongs_to :diver
end

app/models/pen.rb
class Pen < ApplicationRecord
  belongs_to :lease
  has_many :mortality_forms
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :feed
  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one :feed
  mount_uploader :image, ImageUploader


  def full_name
    "#{self.first_name} #{self.last_name}".split.map(&:capitalize).join(' ')
  end

  private

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  has_one :profile
  has_one :feed, through: :profile
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy

  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships

  def follow(other_user)
      following << other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end
  #
  def following?(other_user)
    following.include?(other_user)
  end

  def profile_id
    Profile.find_by(user_id: self.id)
  end


end

app/controllers/divers_controller.rb
class DiversController < ApplicationController
  before_action :set_diver, only: [:show, :edit, :update, :destroy]

  # GET /divers
  def index
    @divers = Diver.all
  end

  # GET /divers/1
  def show
  end

  # GET /divers/new
  def new
    @diver = Diver.new
  end

  # GET /divers/1/edit
  def edit
  end

  # POST /divers
  def create
    @diver = Diver.new(diver_params)

    if @diver.save
      redirect_to @diver, notice: 'Diver was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /divers/1
  def update
    if @diver.update(diver_params)
      redirect_to @diver, notice: 'Diver was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /divers/1
  def destroy
    @diver.destroy
    redirect_to divers_url, notice: 'Diver was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diver
      @diver = Diver.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def diver_params
      params.require(:diver).permit(:first_name, :last_name, :email, :contact, :address, :secondary_contact)
    end
end

app/controllers/feed_controller.rb
class FeedController < ApplicationController
  def show
    @post = Post.new
    @posts = FeedPostFetcher.new(current_user: current_user).run
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  def show
    @facade = FeedShowFacade.new(feed: feed)
  end
end

app/controllers/pens_controller.rb
class PensController < ApplicationController
  before_action :set_pen, only: [:show, :edit, :update, :destroy]

  # GET /pens
  def index
    @pens = Pen.all
  end

  # GET /pens/1
  def show
    respond_to do |format|
      format.html do
causes = [ :bird_strikes, :seal_strikes, :skinny, :deformities, :unknown ]
dates = MortalityForm.all.group_by{|x| x.date}
@reports = MortalityForm.where(date: (Time.now - 1.week)..Time.now, pen: @pen).includes(:diver)
.group_by{|x| x.date.strftime("%Y-%m-%d")}
@causes = causes.map { |cause| { name: cause.id2name.split("_").join(" ").capitalize, data: dates.map{ |date, v| [[date.strftime("%Y-%m-%d"), v[0][cause]] ] }.sum   } }

@mortalities ||= MortalitySearcher.new(
  start_date: Date.current,
  end_date: Date.current
).run
@mortality_totals = totals

end
  format.js do
    @reports = mortality_search
  end

end

  end

  # GET /pens/new
  def new
    @leases = Lease.all
    @pen = Pen.new
    @pens = Pen.all
  end

  # GET /pens/1/edit
  def edit
  end

  def mortality_search
    start_date = params[:search_begin].to_date
    end_date = params[:search_end].to_date
    @mortality_search ||= MortalityForm.where(date: start_date..end_date, pen: @pen).includes(:diver).group_by{|x| x.date.strftime("%Y-%m-%d")}
  end

  def search
    @facade = Profiles::ProfileIndexFacade.new(query: params[:query]).run
  end

  # POST /pens
  def create
    @pen = Pen.new(pen_params)

    if @pen.save
      redirect_to @pen, notice: 'Pen was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /pens/1
  def update
    if @pen.update(pen_params)
      redirect_to @pen, notice: 'Pen was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /pens/1
  def destroy
    @pen.destroy
    redirect_to pens_url, notice: 'Pen was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pen
      @pen = Pen.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def pen_params
      params.require(:pen).permit(:name, :lease_id, :latitude, :longitude)
    end

    def totals
      {

        bird_strikes: @mortalities.map{|total| total.bird_strikes}.sum,
        seal_strikes: @mortalities.map{|total| total.seal_strikes}.sum,
        skinny: @mortalities.map{|total| total.skinny}.sum,
        deformities: @mortalities.map{|total| total.deformities}.sum,
        unknown: @mortalities.map{|total| total.unknown}.sum
      }
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create

      post = Post.create(
        title: params[:post][:title],
        content: params[:post][:content],
        image: params[:post][:image],
        user_id: params[:user_id],
        feed_id: params[:feed_id]
      )

      redirect_to user_feed_path(id: params[:feed_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, except: [:destroy]

  def new
  end

  def create
    user = Users::UserCreateFacade.new(
      email: params[:email],
      password: params[:password],
      first_name: params[:first_name],
      last_name: params[:last_name],
    ).run

    flash[:success] = "Account for #{user.email} successfully created"
    redirect_to user_sessions_path

    rescue Users::UserCreateFacade::UserAlreadyExists
      flash[:danger] = "Account for email already exists"
      redirect_to new_user_sessions_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/divers_helper.rb
module DiversHelper
end

app/helpers/leases_helper.rb
module LeasesHelper
end

app/helpers/pens_helper.rb
module PensHelper
end

app/views/shared/_feed.html.erb
<% posts.each do |post| %>
  <div class="card mb-4 text-center feed-card-container">
    <div class="card-body">
      <%= image_tag post[:image], class: "post-image" if post[:image] %>
      <h5 class="card-title"><%= post[:title]&.capitalize %></h5>
      <p class="card-text"><%= post[:content] %></p>
      <ruby class="card-text">
        <rt><%= post[:first_name] %> <%= post[:last_name] %></rt>
      </ruby>
    </div>
  </div>
<% end %>

app/views/shared/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, other_user.id %></div>
  <%= f.submit "Follow", class: "btn btn-sm btn-primary" %>
<% end %>

app/views/shared/_follow_details.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

<% unless current_user == other_user %>
  <div id="follow_form" class="mt-3 mb-3">
    <% if current_user.following?(other_user) %>
      <%= render 'shared/unfollow' %>
    <% else %>
      <%= render 'shared/follow', other_user: other_user %>
    <% end %>
  </div>
<% end %>

app/views/shared/_login_box.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-md-12">
      <div class="row">
        <div class="col-md-6 mx-auto">
          <div class="card login-card">
            <div class="card-body">
              <div class="text-center" style="text-align: center;">
                Image here
              </div>
            </br>
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_mortality_reports.html.erb
<div class="col-md-12">
  <ul class="list-group">

  <% reports.each do |key, rep| %>
    <div class="col-md-12 mt-4">
    <h4>Report filed on - <%= key %></h4>
    <table class="table table-striped table-bordered table-sm">
      <thead class="table-light">
        <tr>
          <th class="text-center"><div><span>Lease</span></div></th>
          <th class="text-center"><div><span>Pen</span></div></th>
          <th class="text-center"><div><span>Diver</span></div></th>
          <!-- <th class="text-center"><div><span>Date</span></div></th> -->
          <th class="text-center"><div><span>Bird strikes</span></div></th>
          <th class="text-center"><div><span>Seal strikes</span></div></th>
          <th class="text-center"><div><span>Skinny</span></div></th>
          <th class="text-center"><div><span>Deformities</span></div></th>
          <th class="text-center"><div><span>Unknown</span></div></th>
          <th class="text-center"><div><span>Shallow rot</span></div></th>
          <th class="text-center"><div><span>Deep rot</span></div></th>
          <th class="text-center"><div><span>Missing weights</span></div></th>
          <th class="text-center"><div><span>Skin burn</span></div></th>
          <th class="text-center"><div><span>Fish rub</span></div></th>
          <th class="text-center"><div><span>Probe cleaned</span></div></th>
          <th class="text-center"><div><span>Mort comments</span></div></th>
          <th class="text-center"><div><span>Observations</span></div></th>
        </tr>
      </thead>
      <tbody>
        <% rep.each do |mortality_form| %>
          <tr class="">
            <td class="align-middle text-center"><%= mortality_form.lease.name %></td>
            <td class="align-middle text-center"><%= mortality_form.pen.name %></td>
            <td class="align-middle text-center"> <%= mortality_form.diver.initials %></td>
            <%# <%= mortality_form.date %>
            <td class="align-middle text-center"><%= mortality_form.bird_strikes %></td>
            <td class="align-middle text-center"><%= mortality_form.seal_strikes %></td>
            <td class="align-middle text-center"><%= mortality_form.skinny %></td>
            <td class="align-middle text-center"><%= mortality_form.deformities %></td>
            <td class="align-middle text-center"><%= mortality_form.unknown %></td>
            <td class="align-middle text-center"><%= mortality_form.shallow_rot %></td>
            <td class="align-middle text-center"><%= mortality_form.deep_rot %></td>
            <td class="align-middle text-center"><%= mortality_form.missing_weights %></td>
            <td class="align-middle text-center"><%= mortality_form.skin_burn %></td>
            <td class="align-middle text-center"><%= mortality_form.fish_rub %></td>
            <td class="align-middle text-center"><%= mortality_form.probe_cleaned %></td>
            <td class="align-middle text-center"><%= mortality_form.observations %></td>
            <td class="align-middle text-center"><%= mortality_form.mort_comments %></td>
          </tr>

          <% end %>


          <tr class="text-center">
            <th>Total</th>
            <td></td>
            <td></td>
            <td><%= rep.map{|total| total.bird_strikes}.sum %></td>
            <td><%= rep.map{|total| total.seal_strikes}.sum %></td>
            <td><%= rep.map{|total| total.skinny}.sum %></td>
            <td><%= rep.map{|total| total.deformities}.sum %></td>
            <td><%= rep.map{|total| total.unknown}.sum %></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
        </tbody>
      </table>
      <hr>
    </div>
      <% end %>
    </ul>

</div>

app/views/shared/_navigation.html.erb
<!-- <nav class="navbar navbar-expand-lg navbar-light bg-light"> -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Mort</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%# <%= link_to user_profile_path(id: current_user.profile.id), class: "nav-link" do %>
        <%= link_to leases_path, class: "nav-link" do %>
          Leases
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to pens_path, class: "nav-link" do %>
          Pens
        <% end %>
        </li>
        <li class="nav-item">
          <%= link_to mortality_forms_path, class: "nav-link" do %>
            Morts
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to divers_path, class: "nav-link" do %>
          Divers
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to new_mortality_form_path, class: "nav-link" do %>
            Diver Report Form
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to mortality_report_report_path, class: "nav-link" do %>
            Reports
          <% end %>
        </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Actions
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <div class="dropdown-divider"></div>
            <%= link_to user_sessions_path, class: "dropdown-item", method: :delete do %>
              Log Out
            <% end %>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_navigation_social.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">ELS</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to user_profile_path(id: current_user.profile.id), class: "nav-link" do %>
          Profile
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to user_feed_path(id: current_user.feed.id), class: "nav-link"  do %>
          My Feed
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to user_profile_index_path(id: current_user.id), class: "nav-link" do %>
          All Users
        <% end %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Actions
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to edit_user_profile_path(user_id: current_user.id, id: current_user.profile_id), class: "dropdown-item" do %>
            Edit Profile
          <% end %>
          <div class="dropdown-divider"></div>
            <%= link_to user_sessions_path, class: "dropdown-item", method: :delete do %>
              Log Out
            <% end %>
        </div>
      </li>
    </ul>
    <%= form_tag user_profile_index_path(id: params[:user_id]), class: "form-inline my-2 pt-3 my-lg-0", method: :get do %>
    <p>
      <%= text_field_tag :query, params[:query], placeholder: "Search Users" %>
      <%= submit_tag "Search", class: "btn btn-outline-success ml-3 my-2 my-sm-0" %>
    </p>
    <% end %>

  </div>
</nav>

app/views/shared/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @other_user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-sm btn-outline-primary" %>
<% end %>