config/routes.rb
Rails.application.routes.draw do

  get 'mortality_report/show'
  get 'mortality_report/report'
  resources :mortality_forms
  resources :pens
  resources :leases
  resources :divers

  root "user_sessions#new"
   # root "leases#index"
  resource :user_sessions do
    get :new
    get :success
  end

  resources :users, only: [:new, :create] do
    resources :profile, only: [:show, :index, :edit, :update]
    resources :posts, only: [:create]
    resources :feed, only: [:show]
    member do
      get :following, :followers
    end

  end

  resources :relationships, only: [:create, :destroy]
end

app/controllers/leases_controller.rb
class LeasesController < ApplicationController
  before_action :set_lease, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /leases
  def index
    @leases = Lease.all
  end

  # GET /leases/1
  def show
      @pens = Pen.where(lease_id: @lease.id)
      @locations = @pens.map{|pen| {name: pen.name, lat: pen.latitude.to_f, lng: pen.longitude.to_f} }

    respond_to do |format|
      format.html
      format.json { render json: { body: @locations }.to_json }
    end
  end

  # GET /leases/new
  def new
    @pens = Pen.all
    @lease = Lease.new
    # @divers = []
  end

  # GET /leases/1/edit
  def edit
  end

  # POST /leases
  def create
    @lease = Lease.new(lease_params)

    if @lease.save
      redirect_to @lease, notice: 'Lease was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /leases/1
  def update
    if @lease.update(lease_params)
      redirect_to @lease, notice: 'Lease was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /leases/1
  def destroy
    @lease.destroy
    redirect_to leases_url, notice: 'Lease was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lease
      @lease = Lease.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def lease_params
      params.require(:name).permit(:lease)
    end
end

app/helpers/leases_helper.rb
module LeasesHelper
end

app/views/leases/_form.html.erb
<%= form_with(model: lease, local: true) do |form| %>
  <% if lease.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lease.errors.count, "error") %> prohibited this lease from being saved:</h2>

      <ul>
        <% lease.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/leases/edit.html.erb
<h1>Editing Lease</h1>

<%= render 'form', lease: @lease %>

<%= link_to 'Show', @lease %> |
<%= link_to 'Back', leases_path %>

app/views/leases/index.html.erb
<p id="notice"><%= notice %></p>

<div class='row'>
  <div class='col-md-12 space-between'>
    <h1>Leases</h1>
    <div>
      <%= link_to new_lease_path, class: "btn btn-success" do |x| %>
      Create Lease <span class="ml-2"><%= fa_icon "plus"%></span>
      <% end %>
    </div>

  </div>
</div>
<hr>

    <table class="table table-striped table-bordered">
      <thead class="table-light">
        <tr>
          <th>Name</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @leases.each do |lease| %>
          <tr>
            <td>
              <%= link_to lease do |x| %>
              <%= lease.name %>
              <% end %>
            </td>
            <td class="action-td" style="width: 1px;">
              <div class="btn-group">
                <%= link_to lease do %>
                <button type="button" class="btn btn-primary">
                  View
                </button>
                <% end %>

                <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <span class="sr-only">Toggle Dropdown</span>
                </button>
                <div class="dropdown-menu">


                  <%= link_to 'Edit', edit_lease_path(lease), class: "dropdown-item" %>

                  <div class="dropdown-divider"></div>
                  <%= link_to lease, method: :delete,  data: { confirm: 'Are you sure?' }, class: "dropdown-item" do |x| %>
                    <span class="trash-icon mr-2">Delete</span><span class="trash-icon mr-2"><%= fa_icon "trash"%></span>
                  <% end %>
                </div>
              </div>
            </td>

          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

app/views/leases/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h1>New Lease</h1>

      <%= render 'form', lease: @lease %>
    </div>
  </div>
</div>
<%# <%= link_to 'Back', leases_user_path %>

app/views/leases/show.html.erb
<p id="notice"><%= notice %></p>
  <div class="row">
    <div class="col-12">

      <div class='row'>
        <div class='col-md-12 space-between'>
          <div class='space-between h-center'>
            <%= link_to leases_path, class: "text-primary" do %>
              <%= fa_icon "arrow-left 2x"%>
            <% end %>
            <h1 class="mb-0 ml-3"><%= @lease.name %></h1>
            </div>
          <div>
            <%= link_to edit_lease_path(@lease), class: "btn btn-primary" do |x| %>
          <%= fa_icon "edit"%><span class="ml-2"> Edit Lease</span>
            <% end %>
          </div>

        </div>
      </div>
      <hr>

      <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item">
          <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Pens</a>
        </li>
        <!-- <li class="nav-item">
          <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">Contact</a>
        </li> -->
      </ul>
      <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">

          <div class="row">
          <div class="col-md-12 mt-3 mb-1">
            <h4>Pens</h4>
            </div>
            <div class="col-md-4">
              <ul class="list-group">
                <% @pens.each do |pen| %>
                  <%= link_to pen do |x| %>
                  <li class="list-group-item">
                   <%= pen.name %>
                  </li>
                  <% end %>
                <% end %>
              </ul>
            </div>
            <div class="col-md-6">
              <div id="map" style='width: 100%; height: 400px;'></div>
            </div>
            </div>

        <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">

          <div class="row">
          <div class="col-md-12 mt-3 mb-3">
            <h4>Pens</h4>
            </div>
            <div class="col-md-6">
              <ul class="list-group">
                <% @pens.each do |pen| %>
                  <%= link_to pen do |x| %>
                  <li class="list-group-item">
                   <%= pen.name %>
                  </li>
                  <% end %>
                <% end %>
              </ul>
            </div>
            <div class="col-md-6">
              <div id="map" style='width: 100%; height: 400px;'></div>
            </div>
            </div>

        </div>
      </div>
    </div>
  </div>
  <%= link_to 'Edit', edit_lease_path(@lease) %> |
  <%= link_to 'Back', leases_path %>



<script>

function initMap() {
  let locations = []
  fetch('./1.json') // Call the fetch function passing the url of the API as a parameter
  .then(function(response) {
   return response.json();
 }).then(function(res) {

   locations = res.body
   var uluru = {lat: -25.344, lng: 131.036};

  var map = new google.maps.Map(
    document.getElementById('map'), {zoom: 6, center: locations[0]}
  );

  res.body.forEach(function(coords) {

    var contentString = '<div id="content">'+
       '<div id="siteNotice">'+
       '</div>'+
       '<h5 id="firstHeading" class="firstHeading">Pen</h5>'+
       '<div id="bodyContent">'+
       `<p><b>${coords.name} </b></p>` +
       '</div>'+
       '</div>';

    var infowindow = new google.maps.InfoWindow({
       content: contentString
     });

    var marker = new google.maps.Marker({ position: { lat:coords.lat , lng: coords.lng }, map: map })

    marker.addListener('click', function() {
      infowindow.open(map, marker);
    });

  });


 });
}




$( document ).ready(function() {
});
</script>

app/views/leases/show.js.erb
debugger